### ISSUE TITLE
write documentation for how to update DNS

### ISSUE THREAD

**Issue by tahabi** [ocf/dns#9]
running the makefile, why updating the serial matters, etc.

**Comment by tahabi** [comment]
#10 addresses some of this

**Comment by matthew-mcallister** [comment]
I think it's good enough to close this. Additional information would be nothing but a tutorial on DNS, which isn't relevant as far as updating this repo goes.

**Comment by tahabi** [comment]
Doesn't need to be a tutorial on DNS, just relevant things on handling DNS here, like remembering to add reserved names to various places or things like that, etc. etc. SMs know what they should do in other places when updating DNS and vice versa, but this should be documented on principle because otherwise it's just, to quote @daradib, the "obscure knowledge of some SM"

**Comment by matthew-mcallister** [comment]
We don't actually add hostnames to the reserved username list, or reject hostnames as usernames at all. (Maybe that would be useful, but it's not relevant here.)

Contrary to your appeal to @daradib's words, knowledge of DNS is not "obscure" but actually very commonplace. I would welcome a link to a good primer on DNS configuration in the README, however, rather than writing one of our own.

**Comment by chriskuehl** [comment]
i'm prepping a PR to add more details about ocf-specific DNS things

**Comment by tahabi** [comment]
That's not what I mean, the instructions for editing records is absolutely relevant, nor am I claiming that knowledge of DNS is "obscure", obviously it isn't, but the process by which we maintain records is clearly not well known (otherwise nick wouldn't have made the changes manually). That fact alone should make it worth documenting.

**Comment by matthew-mcallister** [comment]
OK, you can shoot me for forgetting about rDNS, as it is already mentioned on the "adding new hosts" page.

**Comment by matthew-mcallister** [comment]
If you want to hear a better explanation, what I object to is describing "why updating the serial matters" in our README, since that is general information. On the other hand, reminding to update the serial number after manually editing the ASUC DNS zone is helpful and relevant to the repo.

The authority information outlined in @chriskuehl's PR is of course also very helpful, but not specific to this issue.
